import { PDFDocument, rgb } from 'pdf-lib'
import fontkit from '@pdf-lib/fontkit'
import fs from 'fs'
import path from 'path'

type VipLevel = 'VIP1' | 'VIP2' | 'VIP3'

type DailyReportInput = {
  date: string
  market: string
  vipLevel: VipLevel
  riskLevel: 'LOW' | 'MID' | 'HIGH'
  judgement: string
  scenarios: { title: string; probability: number }[]
}

export async function generateVipDailyReportPdf(
  input: DailyReportInput
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create()
  pdf.registerFontkit(fontkit)

  const page = pdf.addPage([595, 842])
  const width = page.getWidth()

  const fontPath = path.join(
    process.cwd(),
    'public/fonts/NotoSansKR-Regular.ttf'
  )
  const fontBytes = fs.readFileSync(fontPath)
  const font = await pdf.embedFont(fontBytes)

  let y = 800

  const colors = {
    bg: rgb(0.05, 0.05, 0.08),
    white: rgb(1, 1, 1),
    gray: rgb(0.7, 0.7, 0.7),
    risk: {
      LOW: rgb(0.2, 0.8, 0.4),
      MID: rgb(0.95, 0.7, 0.2),
      HIGH: rgb(0.95, 0.3, 0.3),
    },
  }

  // ===== Header =====
  page.drawRectangle({
    x: 0,
    y: 780,
    width,
    height: 62,
    color: colors.bg,
  })

  page.drawText('SIGNAL · VIP DAILY REPORT', {
    x: 40,
    y: 815,
    size: 18,
    font,
    color: colors.white,
  })

  page.drawText(input.date, {
    x: width - 160,
    y: 815,
    size: 10,
    font,
    color: colors.gray,
  })

  y = 740

  const section = (title: string) => {
    page.drawText(title, {
      x: 40,
      y,
      size: 14,
      font,
      color: colors.white,
    })
    y -= 6
    page.drawLine({
      start: { x: 40, y },
      end: { x: width - 40, y },
      thickness: 1,
      color: colors.gray,
    })
    y -= 20
  }

  const text = (t: string, size = 12) => {
    page.drawText(t, {
      x: 40,
      y,
      size,
      font,
      color: colors.white,
      maxWidth: width - 80,
      lineHeight: size * 1.5,
    })
    y -= size * 1.8
  }

  // ===== Market Summary =====
  section('Market Summary')
  text(`Market: ${input.market}`)
  text(`VIP Level: ${input.vipLevel}`)
  text(`Risk Level: ${input.riskLevel}`)

  // Risk Badge
  page.drawRectangle({
    x: 200,
    y: y + 6,
    width: 80,
    height: 22,
    color: colors.risk[input.riskLevel],
  })
  page.drawText(input.riskLevel, {
    x: 222,
    y: y + 12,
    size: 10,
    font,
    color: colors.white,
  })

  y -= 40

  // ===== Judgement (VIP 분기) =====
  section('AI Judgement')
  if (input.vipLevel === 'VIP1') {
    text('고급 판단은 VIP3 이상에서 제공됩니다.', 11)
  } else {
    text(input.judgement)
  }

  // ===== Scenarios (VIP 분기) =====
  section('Probability Scenarios')

  const scenarios =
    input.vipLevel === 'VIP1'
      ? input.scenarios.slice(0, 1)
      : input.vipLevel === 'VIP2'
      ? input.scenarios.slice(0, 2)
      : input.scenarios

  scenarios.forEach((s) =>
    text(`• ${s.title} (${s.probability}%)`)
  )

  if (input.vipLevel !== 'VIP3') {
    y -= 10
    text('※ 전체 시나리오는 VIP3에서 제공됩니다.', 10)
  }

  // ===== Footer =====
  page.drawText(
    'Generated by SIGNAL · VIP Intelligence Engine',
    {
      x: 40,
      y: 30,
      size: 9,
      font,
      color: colors.gray,
    }
  )

  return await pdf.save()
}
