import { renderPdfByCloudRun } from '@/lib/pdf/cloudRunPdfClient'

/**
 * VIP 도메인 타입
 */
export type VipLevel = 'VIP1' | 'VIP2' | 'VIP3'

/**
 * 🔴 EXTREME 구간 (차트 가로 비율 기준)
 */
export type ExtremeZone = {
  startRatio: number // 0 ~ 1
  endRatio: number   // 0 ~ 1
}

/**
 * VIP Daily Report Input
 */
export type DailyReportInput = {
  date: string
  market: string
  vipLevel: VipLevel
  riskLevel: 'LOW' | 'MID' | 'HIGH'
  judgement: string
  scenarios: {
    title: string
    probability: number
  }[]

  /** 🔥 차트 이미지 (base64) */
  chartBase64: string

  /** 🔥 EXTREME 구간 메타데이터 */
  extremeZones?: ExtremeZone[]
}

/**
 * 1️⃣ VIP Daily Report HTML 생성 (A4 / Dark / Print-safe)
 * - 차트 이미지
 * - EXTREME 빨간 오버레이 포함
 */
function buildVipDailyReportHtml(input: DailyReportInput): string {
  const visibleScenarios =
    input.vipLevel === 'VIP1'
      ? input.scenarios.slice(0, 1)
      : input.vipLevel === 'VIP2'
      ? input.scenarios.slice(0, 2)
      : input.scenarios

  const riskColor =
    input.riskLevel === 'LOW'
      ? '#2ecc71'
      : input.riskLevel === 'MID'
      ? '#f1c40f'
      : '#e74c3c'

  const extremeOverlays =
    input.extremeZones?.map(
      (z) => `
        <div
          class="extreme-zone"
          style="
            left: ${z.startRatio * 100}%;
            width: ${(z.endRatio - z.startRatio) * 100}%;
          "
        ></div>
      `
    ).join('') ?? ''

  return `
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8" />
<style>
@page {
  size: A4;
  margin: 40px;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Noto Sans KR', Arial, sans-serif;
  background: #0d0f1a;
  color: #ffffff;
  font-size: 13px;
  line-height: 1.6;
}

h1 {
  font-size: 22px;
  margin: 0 0 6px 0;
}

.header {
  border-bottom: 1px solid #2a2f45;
  padding-bottom: 14px;
  margin-bottom: 28px;
}

.date {
  color: #9aa0b5;
  font-size: 12px;
}

.section {
  margin-bottom: 26px;
}

.section-title {
  font-size: 15px;
  margin-bottom: 10px;
  border-left: 4px solid #4c6ef5;
  padding-left: 10px;
}

.kv {
  margin: 4px 0;
}

.badge {
  display: inline-block;
  padding: 3px 10px;
  border-radius: 6px;
  background: ${riskColor};
  color: #000;
  font-size: 11px;
  margin-left: 6px;
}

.scenario {
  margin: 6px 0;
}

.notice {
  font-size: 11px;
  color: #9aa0b5;
  margin-top: 8px;
}

/* ===== Chart & EXTREME ===== */
.chart-wrapper {
  position: relative;
  margin-top: 18px;
}

.chart-wrapper img {
  width: 100%;
  border-radius: 8px;
  border: 1px solid #2a2f45;
  display: block;
}

.extreme-zone {
  position: absolute;
  top: 0;
  bottom: 0;
  background: rgba(239, 68, 68, 0.28);
  border-left: 1px solid rgba(239, 68, 68, 0.7);
  border-right: 1px solid rgba(239, 68, 68, 0.7);
}

/* ===== Footer ===== */
.footer {
  margin-top: 60px;
  font-size: 11px;
  color: #7b8099;
  text-align: center;
  border-top: 1px solid #2a2f45;
  padding-top: 14px;
}

.watermark {
  position: fixed;
  bottom: 20px;
  right: 30px;
  font-size: 72px;
  color: rgba(255,255,255,0.04);
  transform: rotate(-20deg);
  pointer-events: none;
}
</style>
</head>

<body>

<div class="watermark">${input.vipLevel}</div>

<div class="header">
  <h1>SIGNAL · VIP DAILY REPORT</h1>
  <div class="date">${input.date}</div>
</div>

<div class="section">
  <div class="section-title">Market Summary</div>
  <div class="kv">Market: ${input.market}</div>
  <div class="kv">
    Risk Level:
    <span class="badge">${input.riskLevel}</span>
  </div>
  <div class="kv">VIP Level: ${input.vipLevel}</div>
</div>

<div class="section">
  <div class="section-title">Market Chart</div>
  <div class="chart-wrapper">
    <img src="${input.chartBase64}" />
    ${extremeOverlays}
  </div>
</div>

<div class="section">
  <div class="section-title">AI Judgement</div>
  ${
    input.vipLevel === 'VIP1'
      ? `<div>상세 판단은 VIP3 이상에서 제공됩니다.</div>`
      : `<div>${input.judgement}</div>`
  }
</div>

<div class="section">
  <div class="section-title">Probability Scenarios</div>
  ${visibleScenarios
    .map(
      (s) =>
        `<div class="scenario">• ${s.title} (${s.probability}%)</div>`
    )
    .join('')}
  ${
    input.vipLevel !== 'VIP3'
      ? `<div class="notice">※ 전체 시나리오는 VIP3 전용 콘텐츠입니다.</div>`
      : ''
  }
</div>

<div class="footer">
  Generated by SIGNAL · VIP Intelligence Engine<br/>
  This report is confidential and intended for VIP members only.
</div>

</body>
</html>
`
}

/**
 * 2️⃣ 최종 PDF 생성
 */
export async function generateVipDailyReportPdf(
  input: DailyReportInput
): Promise<Buffer> {
  const html = buildVipDailyReportHtml(input)
  return renderPdfByCloudRun(html)
}
